title: Alya Nur Hanifah 
logo: "/IMAGE/image.png?raw=true" 
description: >
  About Myself
  <br><br>
  Description
  <br><br>
  <a href="https://www.linkedin.com/in/alya-nur-hanifah-056179181?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BLFIsHg2HTYqyacxeAFpQcw%3D%3D">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
